 name: BlockReplacer
 version: 0.1
 description: First test of BlockReplacer!
 author: Alekso56
 main: io.github.alekso56.BlockReplacer
 database: false
 
 commands:
   test:
     description: spam a bit
     aliases: [spam_me,spamMe]
     permission: BlockReplacer.test
     usage: Syntax error! Simply type /&lt;command&gt;
 
 permissions:
   BlockReplacer.*:
     description: Gives access to all BlockReplacer commands
     children:
       BlockReplacer.test: true
   BlockReplacer.test:
     description: spam abit
     default: true